### ISSUE TITLE
Přidávání Listu

### ISSUE THREAD

**Issue by jakubmacak** [lukaswojnar/gift-registry#10]

**Comment by jakubmacak** [comment]
@ovyhlidal Ahoj, jak to vypadá s Listem? :)

**Comment by ovyhlidal** [comment]
Ahoj, prave to jdu dodelavat. Psal jsem jeste eseje do Informacni spolecnosti :/

**Comment by ovyhlidal** [comment]
@kmaci Pridavani seznamu mam hotovy, je to pushnuty. Ted jsem ale premyslel nad tim, jak budeme pridavat ty darky k seznamu? Udelame to tak, ze pri vytvareni seznamu budu moct pridavat darky, nebo vytvorim seznam, pak kliknu na edit a tam az budu moct pridavat darky? Nebo tam bude jen tlacitko pridat darek, ktery te redirectne na formular pro vytvoreni darku?

**Comment by jakubmacak** [comment]
Myslím si, že nejlepší by bylo mít seznam a tam mít tlačítko přidat dárek. Formulář na přidávání by mohl klidně být v modálním okně, aby se to furt nepřesměrovávalo někam jinam...

**Comment by ovyhlidal** [comment]
Souhlasim, to se mi libi :) Jdu se podivat, jak se delaji modalni okna v railsech, s nima jsem jeste nedelal ...

**Comment by jakubmacak** [comment]
Myslím si, že bude stačit dát formulář na adrese /lists/:id/gifts/new do modální okna, které se dá ve Foundation vytvořit snadno (http://foundation.zurb.com/sites/docs/v/5.5.3/components/reveal.html).

**Comment by ovyhlidal** [comment]
Mrknu na to, Diky :)

**Comment by jakubmacak** [comment]
Přidávání dárku už jde přes modální okno :)

**Comment by ovyhlidal** [comment]
Husty super :) Jsem se do toho chtel pustit jak dorazim do Brna ... Takze co dal?

**Comment by jakubmacak** [comment]
Chtěl jsem se teď mrknout na správu rolí, tak jestli bys mrknul třeba na ty notifikace nebo cokoli, co ještě v Issues je :)

**Comment by ovyhlidal** [comment]
Oka podivam se na notifikace nebo muzu pridat jeste nejakou tu udalost ....
