### ISSUE TITLE
Seznam Wishlistu uzivatele neobsahuje jmeno 

### ISSUE THREAD

**Issue by ovyhlidal** [lukaswojnar/gift-registry#13]
Seznam Wishlistu uzivatele neobsahuje jmeno, misto jmena je napsano "Some name". Opravim

**Comment by lukaswojnar** [comment]
Problém je ale v tom, že si uživatel aktuálně nemůže jméno nastavit/změnit - neexistuje profil. Proto jsem říkal, že ho udělám.

**Comment by ovyhlidal** [comment]
Ok, prozatim jsem tam nastavil email ;)

**Comment by jakubmacak** [comment]
Profil je určitě třeba dodělat.

**Comment by lukaswojnar** [comment]
Udělám to. V Trellu jsem si na to vytvořil kartičku a přidal jsem se k ní. Přidejte si taky prosím karty, ať víme, co kdo dělá a neděláme zbytečně něco 2x.
