### ISSUE TITLE
List neobsahuje event_date

### ISSUE THREAD

**Issue by ovyhlidal** [lukaswojnar/gift-registry#17]
Pridam migraci pro pridani event_date k listu. 
@lukaswojnar @kmaci

**Comment by jakubmacak** [comment]
Ahoj @ovyhlidal, event_date i address byly už v původní migraci (https://github.com/lukaswojnar/gift-registry/blob/master/wishlist/db/migrate/20160119202741_create_lists.rb).

**Comment by ovyhlidal** [comment]
Zajimavy. Ja je tam nemel, kdyz jsem si pullnul nejnovejsi verzi masteru... Hmm asi jsem mel kopletne dropbnou DB, kdyz jsem si udelal update ...

**Comment by ovyhlidal** [comment]
No jasne, ted uz to tam mam... Jdu zrusit ty migrace co jsem pridal ... Chjo. Sorry panove to jsem p... :/

**Comment by ovyhlidal** [comment]
Na tohle totiz rake db:migrate nestacil ... Musel jsem celou db dropnout a znova vytvorit ... :/

**Comment by jakubmacak** [comment]
Jj, při změně používám raději příkaz `rake db:drop db:create db:migrate`.

**Comment by ovyhlidal** [comment]
Presne tak, ja od ted uz taky...
