### ISSUE TITLE
Nasazeni aplikace?

### ISSUE THREAD

**Issue by ovyhlidal** [lukaswojnar/gift-registry#3]
Ahoj @lukaswojnar @kmaci 

budeme aplikaci nekam nasazovat, nebo bude stacit kdyz to budeme prezentovat na nejakem pc?

**Comment by jakubmacak** [comment]
Nasadil bych ji na Heroku, nejedná se o nic moc náročného.

**Comment by ovyhlidal** [comment]
Ok :) Jak si ted rozdelime prace? Ja bych s tim chtel co nejvic ted pohnout at to mame do 30.1. hotovy, protoze ja potom jedu pryc a nechci aby to bylo nedodelany ... @kmaci 
Co @lukaswojnar  chces se ucastnit na projektu nebo jak to mas?

**Comment by jakubmacak** [comment]
Jj, práci si klidně rozdělme.
@ovyhlidal Máš teď něco rozdělaného?

**Comment by ovyhlidal** [comment]
Upne ne, zacal jsem delat controller pro pridavani seznamu ... Takze to asi dodelam. Kdyz si pullnes master, tak uvidis...

**Comment by jakubmacak** [comment]
V podmínkách projektu je uvedeno, že aplikace musí běžet na OpenShiftu nebo Heroku.
Každopádně musíme rozšířit modely, abychom jich měli alespoň těch 7. Co přidáme?

**Comment by ovyhlidal** [comment]
Ted mame 3 - User, Gift, List. 
Muzeme rozsirit uzivatele o avatar? Coz nam teda nezvedne pocet datovych modelu... 
Napada me neco jako "udalost ke ktere tvorim Wishlist" Nemuselo by to byt povinny, ale dejme tomu, kdyby uzivatel chtel udelat seznam darku na svatbu, tak by mohl vytvorit nejaky popis udalosti a ten by se zobrazil pri vytvareni seznamu... ?

**Comment by jakubmacak** [comment]
Jj, událost je dobrý nápad. Tak ještě 3 :) Budu přemýšlet.

**Comment by jakubmacak** [comment]
Co třeba nějaké notification? Vztah dárek-uživatel (e-mail) + datum, kdy má být notifikace zaslána (kolik dnů předem)?

**Comment by ovyhlidal** [comment]
Jo to je super :+1: 
Pridal jsem pro Notification issue: https://github.com/lukaswojnar/gift-registry/issues/9
A taky pro Udalost: https://github.com/lukaswojnar/gift-registry/issues/8

**Comment by jakubmacak** [comment]
Co udělat jednoduchý shopping list? Modely shopping_list (name, date), item (name). Prostě jednoduchý nákupní seznam...

**Comment by ovyhlidal** [comment]
Muzeme. Udelame to pro uzivatele, ktery je zaregistrovani do vice wishlistu a on bude moct videt seznam vsech darku co ma poridit a do kdy?

**Comment by jakubmacak** [comment]
No myslím si, že pak by se ale nemusely dělat nové modely.

**Comment by ovyhlidal** [comment]
Oka, klidne muzeme ...
