### ISSUE TITLE
Testy

### ISSUE THREAD

**Issue by ovyhlidal** [lukaswojnar/gift-registry#7]
Ahoj, mam zkusit napsat par testu? Abychom pak mohli rict, ze tam mame treba plne otestovany model? Nebo tak neco?

**Comment by jakubmacak** [comment]
Dobrá otázka. Pak bychom ale měli testovat všechno, ne? Jinak předpokládám, že nějaké změny v modelech ještě budou.

**Comment by ovyhlidal** [comment]
No teoreticky muzeme, ale to je brutalne moc prace ... Ja si myslim, ze pro demonstraci toho, ze jsme se neco naucili bude stacit napsat par testu. To si klidne vemu na starost. Dopisu pridavani sezamu a pak se vrhnu na tohle. 
Co se tyka zmen v modelu tak asi jeste budou - treba gift by mel mit i nejaky status - assigned/unassigned to_user. 
List bude muset mit nekde ulozeny ten token a uzivatele s tokenem ho budou moct upravovat ...

**Comment by lukaswojnar** [comment]
Psaní testů nebylo v požadavcích, tak bych s tím neztrácel moc času.
